# Generated by Django 5.2.17 on 2026-09-24 13:53

import content.models
import content.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('alt', models.CharField(max_length=250, verbose_name='Texto alternativo / descripción')),
                ('file', models.FileField(help_text='JPG, PNG, WebP o PDF. Máximo 15 MB. Biblioteca de archivos destinados a publicación; no subir documentos privados.', upload_to=content.models.upload_path, validators=[content.validators.validate_upload], verbose_name='Subir desde dispositivo')),
                ('kind', models.CharField(choices=[('image', 'Imagen'), ('pdf', 'PDF')], editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'archivo multimedia',
                'verbose_name_plural': 'Biblioteca multimedia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('title', models.CharField(max_length=120, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('requirements', models.TextField(blank=True, help_text='Un punto por línea.', verbose_name='Datos a solicitar al cliente')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'servicio',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('agricola', 'Agrícola'), ('construccion', 'Construcción'), ('implementos', 'Implementos')], max_length=20, unique=True, verbose_name='Categoría')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre visible')),
                ('subtitle', models.CharField(blank=True, max_length=120, verbose_name='Subtítulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('image', models.ForeignKey(limit_choices_to={'kind': 'image'}, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='content.mediaasset', verbose_name='Imagen de biblioteca')),
            ],
            options={
                'verbose_name': 'categoría',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('primary', models.BooleanField(default=False, verbose_name='Marca principal')),
                ('active', models.BooleanField(default=True, verbose_name='Publicada')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('image', models.ForeignKey(limit_choices_to={'kind': 'image'}, on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='content.mediaasset', verbose_name='Imagen de biblioteca')),
            ],
            options={
                'verbose_name': 'marca',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(verbose_name='Resumen')),
                ('body', models.TextField(help_text='Texto normal; separa párrafos con saltos de línea.', verbose_name='Contenido')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('image', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='content.mediaasset', verbose_name='Imagen de biblioteca')),
            ],
            options={
                'verbose_name': 'novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('model', models.CharField(max_length=120, verbose_name='Modelo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado en Inicio')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('mock', models.BooleanField(default=False, verbose_name='Ficha de demostración')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.brand', verbose_name='Marca')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Característica')),
                ('value', models.CharField(max_length=180, verbose_name='Valor')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Unidad')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='content.product')),
            ],
            options={
                'verbose_name': 'especificación técnica',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('excerpt', models.TextField(verbose_name='Resumen')),
                ('body', models.TextField(verbose_name='Contenido')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('start', models.DateTimeField(verbose_name='Inicio del evento')),
                ('end', models.DateTimeField(verbose_name='Fin del evento')),
                ('place', models.CharField(max_length=180, verbose_name='Lugar')),
                ('image', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='content.mediaasset', verbose_name='Imagen de biblioteca')),
            ],
            options={
                'verbose_name': 'evento',
                'ordering': ['-start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='event_valid_period')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=180, verbose_name='Subtítulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('start', models.DateTimeField(verbose_name='Inicio de publicación')),
                ('end', models.DateTimeField(verbose_name='Fin de publicación')),
                ('place', models.CharField(blank=True, max_length=180, verbose_name='Lugar')),
                ('button_text', models.CharField(default='Conocer más', max_length=80, verbose_name='Texto del botón')),
                ('href', models.CharField(max_length=500, validators=[content.validators.validate_link], verbose_name='Enlace del botón')),
                ('active', models.BooleanField(default=False, verbose_name='Activa')),
                ('show_home', models.BooleanField(default=True, verbose_name='Mostrar dentro del Inicio')),
                ('show_popup', models.BooleanField(default=False, verbose_name='Mostrar popup al entrar')),
                ('frequency', models.CharField(choices=[('session', 'Una vez por sesión'), ('visit', 'Cada visita'), ('day', 'Una vez por día')], default='session', max_length=10, verbose_name='Frecuencia')),
                ('paths', models.TextField(blank=True, help_text='Una por línea, por ejemplo / o /maquinaria. Vacío = todas las páginas.', verbose_name='Rutas donde se muestra')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridad (menor primero)')),
                ('desktop_image', models.ForeignKey(limit_choices_to={'kind': 'image'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_desktop', to='content.mediaasset', verbose_name='Imagen escritorio')),
                ('mobile_image', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_mobile', to='content.mediaasset', verbose_name='Imagen móvil')),
            ],
            options={
                'verbose_name': 'campaña',
                'ordering': ['priority', '-start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='campaign_valid_period')],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(limit_choices_to={'kind': 'pdf'}, on_delete=django.db.models.deletion.PROTECT, related_name='product_documents', to='content.mediaasset', verbose_name='PDF de biblioteca (o + para subir)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='content.product')),
            ],
            options={
                'verbose_name': 'documento',
                'constraints': [models.UniqueConstraint(fields=('product', 'asset'), name='unique_product_document')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('asset', models.ForeignKey(limit_choices_to={'kind': 'image'}, on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='content.mediaasset', verbose_name='Seleccionar de biblioteca (o + para subir)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.product')),
            ],
            options={
                'verbose_name': 'imagen',
                'ordering': ['position', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('product', 'asset'), name='unique_product_image')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Morgillo', max_length=120, verbose_name='Nombre de empresa')),
                ('url', models.URLField(default='http://localhost:3000', verbose_name='URL pública del frontend')),
                ('phone', models.CharField(max_length=40, verbose_name='Ventas')),
                ('office', models.CharField(max_length=40, verbose_name='Oficina')),
                ('service', models.CharField(max_length=40, verbose_name='Servicio')),
                ('whatsapp', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^\\d{8,18}$', 'Escribe solo dígitos, incluyendo el código de país.')], verbose_name='WhatsApp (país y número, sin +)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('hours', models.CharField(max_length=180, verbose_name='Horario')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('hero_title', models.CharField(default='Maquinaria para hacer avanzar tus proyectos.', max_length=180, verbose_name='Título del Hero')),
                ('hero_description', models.TextField(default='Soluciones en maquinaria agrícola, construcción e implementos, con respaldo comercial y servicio técnico.', verbose_name='Descripción del Hero')),
                ('company_title', models.CharField(default='Maquinaria que mueve proyectos.', max_length=180, verbose_name='Título de empresa')),
                ('company_description', models.TextField(default='Maquinaria agrícola, construcción e implementos, con asesoría, repuestos y servicio técnico.', verbose_name='Descripción de empresa')),
                ('seo_description', models.CharField(default='Maquinaria agrícola, construcción, implementos, repuestos y servicio técnico.', max_length=250, verbose_name='Descripción SEO')),
                ('hero_image', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_heroes', to='content.mediaasset', verbose_name='Imagen del Hero')),
                ('logo', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='site_logos', to='content.mediaasset', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'configuración general',
                'verbose_name_plural': 'Configuración general',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='singleton_site')],
            },
        ),
    ]
