# Generated by Django 5.2.17 on 2026-10-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_category_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentMediaFile',
            fields=[
                ('name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('size', models.PositiveIntegerField(editable=False)),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
